#ifndef GUARD_CONSTANTS_GOLDEN_YELLOW_PIKACHU_CRIES_H
#define GUARD_CONSTANTS_GOLDEN_YELLOW_PIKACHU_CRIES_H

// Stable semantic IDs from Pokemon Yellow. P9B intentionally supplies PCM
// data only for the 27 IDs classified Required by the locked P9A audit.
enum GoldenYellowPikachuCry
{
    YELLOW_PIKACHU_CRY_01 = 1,
    YELLOW_PIKACHU_CRY_02 = 2,
    YELLOW_PIKACHU_CRY_03 = 3,
    YELLOW_PIKACHU_CRY_04 = 4,
    YELLOW_PIKACHU_CRY_05 = 5,
    YELLOW_PIKACHU_CRY_06 = 6,
    YELLOW_PIKACHU_CRY_07 = 7,
    YELLOW_PIKACHU_CRY_08 = 8,
    YELLOW_PIKACHU_CRY_09 = 9,
    YELLOW_PIKACHU_CRY_10 = 10,
    YELLOW_PIKACHU_CRY_11 = 11,
    YELLOW_PIKACHU_CRY_12 = 12,
    YELLOW_PIKACHU_CRY_13 = 13,
    YELLOW_PIKACHU_CRY_14 = 14,
    YELLOW_PIKACHU_CRY_15 = 15,
    YELLOW_PIKACHU_CRY_16 = 16,
    YELLOW_PIKACHU_CRY_17 = 17,
    YELLOW_PIKACHU_CRY_18 = 18,
    YELLOW_PIKACHU_CRY_19 = 19,
    YELLOW_PIKACHU_CRY_20 = 20,
    YELLOW_PIKACHU_CRY_21 = 21,
    YELLOW_PIKACHU_CRY_22 = 22,
    YELLOW_PIKACHU_CRY_23 = 23,
    YELLOW_PIKACHU_CRY_24 = 24,
    YELLOW_PIKACHU_CRY_25 = 25,
    YELLOW_PIKACHU_CRY_26 = 26,
    YELLOW_PIKACHU_CRY_27 = 27,
    YELLOW_PIKACHU_CRY_28 = 28,
    YELLOW_PIKACHU_CRY_29 = 29,
    YELLOW_PIKACHU_CRY_30 = 30,
    YELLOW_PIKACHU_CRY_31 = 31,
    YELLOW_PIKACHU_CRY_32 = 32,
    YELLOW_PIKACHU_CRY_33 = 33,
    YELLOW_PIKACHU_CRY_34 = 34,
    YELLOW_PIKACHU_CRY_35 = 35,
    YELLOW_PIKACHU_CRY_36 = 36,
    YELLOW_PIKACHU_CRY_37 = 37,
    YELLOW_PIKACHU_CRY_38 = 38,
    YELLOW_PIKACHU_CRY_39 = 39,
    YELLOW_PIKACHU_CRY_40 = 40,
    YELLOW_PIKACHU_CRY_41 = 41,
    YELLOW_PIKACHU_CRY_42 = 42,
    YELLOW_PIKACHU_CRY_COUNT = 42,
};

#define YELLOW_PIKACHU_CRY_NO_PCM 0xFF

#endif // GUARD_CONSTANTS_GOLDEN_YELLOW_PIKACHU_CRIES_H
