#ifndef GUARD_CONSTANTS_GOLDEN_YELLOW_PARTNER_REACTIONS_H
#define GUARD_CONSTANTS_GOLDEN_YELLOW_PARTNER_REACTIONS_H

// Semantic Golden Yellow names retain the original Yellow Emotion IDs so the
// port remains traceable without leaking raw source numbers into story code.
enum GoldenYellowPartnerReaction
{
    GY_PARTNER_REACTION_EMPTY = 0,
    GY_PARTNER_REACTION_NEUTRAL,
    GY_PARTNER_REACTION_HAPPY,
    GY_PARTNER_REACTION_SUBDUED,
    GY_PARTNER_REACTION_PLAYFUL,
    GY_PARTNER_REACTION_DISPLEASED,
    GY_PARTNER_REACTION_IRRITATED,
    GY_PARTNER_REACTION_ENERGETIC_HAPPY,
    GY_PARTNER_REACTION_HAPPY_GRIN,
    GY_PARTNER_REACTION_STRONG_DISPLEASURE,
    GY_PARTNER_REACTION_AFFECTION,
    GY_PARTNER_REACTION_SLEEPING,
    GY_PARTNER_REACTION_FROWNING,
    GY_PARTNER_REACTION_ALOOF,
    GY_PARTNER_REACTION_VERY_ANGRY,
    GY_PARTNER_REACTION_CONTENT,
    GY_PARTNER_REACTION_STRONG_HAPPINESS,
    GY_PARTNER_REACTION_UNHAPPY,
    GY_PARTNER_REACTION_CAPTURE_SUCCESS,
    GY_PARTNER_REACTION_STRONG_AFFECTION,
    GY_PARTNER_REACTION_MAX_AFFECTION,
    GY_PARTNER_REACTION_FISHING,
    GY_PARTNER_REACTION_TOWER_AFRAID,
    GY_PARTNER_REACTION_BILL_CONFUSED,
    GY_PARTNER_REACTION_THUNDER_STONE_REFUSAL,
    GY_PARTNER_REACTION_ELECTRIC_POWER,
    GY_PARTNER_REACTION_PEWTER_JIGGLYPUFF,
    GY_PARTNER_REACTION_BILL_SHOCKED,
    GY_PARTNER_REACTION_STATUS_SICK,
    GY_PARTNER_REACTION_FAN_CLUB_AFFECTION,
    GY_PARTNER_REACTION_FAN_CLUB_MAX_AFFECTION,
    GY_PARTNER_REACTION_BILL_POST_STATE,
    GY_PARTNER_REACTION_BILL_INTERMEDIATE,
    GY_PARTNER_REACTION_COUNT,
};

enum GoldenYellowPartnerReactionCommandType
{
    GY_PARTNER_REACTION_CMD_END,
    GY_PARTNER_REACTION_CMD_CRY,
    GY_PARTNER_REACTION_CMD_BUBBLE,
    GY_PARTNER_REACTION_CMD_MOVEMENT,
    GY_PARTNER_REACTION_CMD_PORTRAIT,
    GY_PARTNER_REACTION_CMD_DELAY,
    GY_PARTNER_REACTION_CMD_TURN_AWAY,
    GY_PARTNER_REACTION_CMD_CALLBACK,
};

enum GoldenYellowPartnerBubble
{
    GY_PARTNER_BUBBLE_SMILE,
    GY_PARTNER_BUBBLE_HEART,
    GY_PARTNER_BUBBLE_SKULL,
    GY_PARTNER_BUBBLE_ZZZ,
    GY_PARTNER_BUBBLE_BOLT,
    GY_PARTNER_BUBBLE_FISH,
    GY_PARTNER_BUBBLE_EXCLAMATION,
    GY_PARTNER_BUBBLE_QUESTION,
};

enum GoldenYellowPartnerMovement
{
    // Yellow source movement labels retained in comments for provenance.
    GY_PARTNER_MOVEMENT_AGITATED_TURN, // PikachuMovementData_fd218
    GY_PARTNER_MOVEMENT_ALOOF_TURN,    // PikachuMovementData_fd21e
    GY_PARTNER_MOVEMENT_ENERGETIC_HOP, // PikachuMovementData_fd224
    GY_PARTNER_MOVEMENT_PLAYFUL_HOP,   // PikachuMovementData_fd230

    // Golden Yellow GBA choreography presets. These never displace the
    // follower from its map tile; they only add safe facing/jump timing around
    // the source-faithful portrait reaction.
    GY_PARTNER_MOVEMENT_HAPPY_BOUNCE,
    GY_PARTNER_MOVEMENT_AFFECTION_BOUNCE,
    GY_PARTNER_MOVEMENT_CELEBRATE,
    GY_PARTNER_MOVEMENT_CONFUSED_LOOK,
    GY_PARTNER_MOVEMENT_REFUSAL_SHAKE,
    GY_PARTNER_MOVEMENT_FEAR_RECOIL,
    GY_PARTNER_MOVEMENT_ELECTRIC_JOLT,
    GY_PARTNER_MOVEMENT_SAD_TURN,
    GY_PARTNER_MOVEMENT_SLEEPY_SWAY,
    GY_PARTNER_MOVEMENT_WEAK_PAUSE,
    GY_PARTNER_MOVEMENT_STARTLED_HOP,
};

enum GoldenYellowPartnerReactionCallback
{
    // These are semantic translations of Yellow's subcommands. P3 deliberately
    // leaves story continuations inert; authored event integration owns them.
    GY_PARTNER_CALLBACK_SHOW_MAP_VIEW,
    GY_PARTNER_CALLBACK_LOAD_FONT,
    GY_PARTNER_CALLBACK_PEWTER_CENTER,
    GY_PARTNER_CALLBACK_FAN_CLUB,
    GY_PARTNER_CALLBACK_BILL_HOUSE,
};

#define GY_PARTNER_CRY_DEFAULT 0xFF
#define GY_PARTNER_CRY_1        1
#define GY_PARTNER_CRY_4        4
#define GY_PARTNER_CRY_5        5
#define GY_PARTNER_CRY_6        6
#define GY_PARTNER_CRY_9        9
#define GY_PARTNER_CRY_10      10
#define GY_PARTNER_CRY_13      13
#define GY_PARTNER_CRY_15      15
#define GY_PARTNER_CRY_19      19
#define GY_PARTNER_CRY_26      26
#define GY_PARTNER_CRY_29      29
#define GY_PARTNER_CRY_31      31
#define GY_PARTNER_CRY_33      33
#define GY_PARTNER_CRY_34      34
#define GY_PARTNER_CRY_35      35
#define GY_PARTNER_CRY_37      37
#define GY_PARTNER_CRY_39      39
#define GY_PARTNER_CRY_40      40

#endif // GUARD_CONSTANTS_GOLDEN_YELLOW_PARTNER_REACTIONS_H
