#include "global.h"
#include "constants/event_object_movement.h"

/*
 * Native follower movement definitions used by the Golden Yellow reaction
 * director. These mirror the corresponding movement scripts in
 * data/scripts/follower.inc byte-for-byte, but live in C because those script
 * labels are assembler-local and therefore cannot satisfy C linker references.
 *
 * Keep these sequences tile-safe. The reaction director runs them through
 * ScriptMovement_StartObjectMovementScript(), then restores normal follower
 * authority before the portrait/field pipeline continues.
 */

const u8 FollowerSkippingMovement[] =
{
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_DELAY_4,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerShiverVerticalMovement[] =
{
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_SLIDE_LEFT,
    MOVEMENT_ACTION_SLIDE_RIGHT,
    MOVEMENT_ACTION_SLIDE_RIGHT,
    MOVEMENT_ACTION_SLIDE_LEFT,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerShiverHorizontalMovement[] =
{
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_SLIDE_UP,
    MOVEMENT_ACTION_SLIDE_DOWN,
    MOVEMENT_ACTION_SLIDE_DOWN,
    MOVEMENT_ACTION_SLIDE_UP,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerLookAway[] =
{
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerLookAwayBark[] =
{
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerLookAwayPokeG[] =
{
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerPokeGround[] =
{
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_DOWN,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerHopFast[] =
{
    MOVEMENT_ACTION_JUMP_IN_PLACE_UP,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_JUMP_IN_PLACE_LEFT,
    MOVEMENT_ACTION_JUMP_IN_PLACE_RIGHT,
    MOVEMENT_ACTION_FACE_PLAYER,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerDizzy[] =
{
    MOVEMENT_ACTION_WALK_IN_PLACE_NORMAL_LEFT,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_RIGHT,
    MOVEMENT_ACTION_WALK_IN_PLACE_SLOW_UP,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_DOWN,
    MOVEMENT_ACTION_DELAY_4,
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerLookAround[] =
{
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_FACE_LEFT,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_FACE_UP,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_FACE_DOWN,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_DELAY_16,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerDance[] =
{
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_JUMP_IN_PLACE_UP,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_UP,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_LEFT,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_RIGHT,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_UP,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_LEFT,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_DOWN,
    MOVEMENT_ACTION_WALK_IN_PLACE_FAST_RIGHT,
    MOVEMENT_ACTION_JUMP_IN_PLACE_UP,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_JUMP_IN_PLACE_UP,
    MOVEMENT_ACTION_FACE_PLAYER,
    MOVEMENT_ACTION_STEP_END,
};

const u8 FollowerStartled[] =
{
    MOVEMENT_ACTION_FACE_AWAY_PLAYER,
    MOVEMENT_ACTION_LOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_JUMP_IN_PLACE_DOWN,
    MOVEMENT_ACTION_UNLOCK_FACING_DIRECTION,
    MOVEMENT_ACTION_FACE_PLAYER,
    MOVEMENT_ACTION_STEP_END,
};
